/**
 * The preservation model.
 *
 * This module exists to hold one distinction absolutely firm:
 *
 *   ORIGINAL      bytes the source served, kept verbatim, never re-written
 *   RECONSTRUCTED KML this tool generated from map geometry it read
 *
 * They are different things with different trustworthiness, and conflating
 * them would be the most damaging thing this tool could do — a reconstructed
 * document presented as the authority's own file invites someone to treat a
 * derived artefact as a record.
 *
 * The distinction is therefore made structural rather than conventional:
 *
 *   - `ArtifactOrigin` is a closed union, and every artefact carries one.
 *   - `SourceFileRecord.origin` is the *literal* type `'original'`. No value
 *     of that type can describe a generated document.
 *   - Original bytes are stored and served exactly as received. They never
 *     pass through the KML builder, so there is no code path that could emit
 *     a re-serialised document wearing an original's name.
 *   - Generated documents are stamped `origin=reconstructed` inside the file
 *     itself, so the label survives leaving this tool.
 */

/** What an artefact fundamentally is. There is no third option. */
export type ArtifactOrigin = 'original' | 'reconstructed';

export const ORIGIN_LABELS: Record<ArtifactOrigin, string> = {
  original: 'Original source file',
  reconstructed: 'Reconstructed from map geometry',
};

export const ORIGIN_DESCRIPTIONS: Record<ArtifactOrigin, string> = {
  original:
    'Retrieved from the source and preserved byte for byte. This is the file the source published, not a ' +
    'copy this tool generated.',
  reconstructed:
    'Generated by this tool from geometry read out of the source. It is not a file the source published, ' +
    'and it must not be presented as one.',
};

/** How a preserved file was reached. Recorded so the find can be retraced. */
export type DiscoveryRoute =
  | 'page-markup'
  | 'inline-script'
  | 'script-bundle'
  | 'map-style'
  | 'service-catalog'
  | 'network-link'
  | 'style-reference'
  | 'overlay-icon'
  | 'seed';

export const ROUTE_LABELS: Record<DiscoveryRoute, string> = {
  'page-markup': 'Linked in the page markup',
  'inline-script': 'Referenced by an inline script',
  'script-bundle': 'Referenced in a JavaScript bundle',
  'map-style': 'Named by the map style document',
  'service-catalog': 'Listed in a service catalog',
  'network-link': 'Reached through a NetworkLink inside another KML',
  'style-reference': 'Reached through a styleUrl in another KML',
  'overlay-icon': 'Referenced as overlay imagery by another KML',
  seed: 'Supplied directly',
};

/** Routes that reach a resource the visible interface never offers. */
export const UNEXPOSED_ROUTES: ReadonlySet<DiscoveryRoute> = new Set([
  'script-bundle',
  'inline-script',
  'network-link',
  'style-reference',
  'overlay-icon',
  'map-style',
]);

export type PreservedFileKind = 'kml' | 'kmz';

/** What was found inside a preserved document, for the catalog listing. */
export type FileInspection = {
  /** The document's own `<name>`, when it declared one. */
  documentName: string | null;
  placemarks: number;
  /** Placemarks that actually carry geometry. */
  withGeometry: number;
  geometryTypes: string[];
  folders: string[];
  /** Outbound links the document declares. */
  networkLinks: number;
  /** True when a link refreshes on a timer, so the file is a live feed. */
  hasRefreshingLinks: boolean;
  /** Entry names inside a KMZ archive. */
  archiveEntries: string[];
  /** Populated when the document could not be parsed; the bytes are kept anyway. */
  parseError: string | null;
};

/**
 * A file retrieved from the source and preserved as-is.
 *
 * `origin` is the literal `'original'`: a `SourceFileRecord` cannot, by
 * construction, describe something this tool generated.
 */
export type SourceFileRecord = {
  id: string;
  readonly origin: 'original';
  url: string;
  /** Final URL after redirects, when it differed. */
  finalUrl: string | null;
  kind: PreservedFileKind;
  /** The filename the source implied, from Content-Disposition or the path. */
  filename: string;
  contentType: string | null;
  byteSize: number;
  /** SHA-256 of the preserved bytes, so integrity can be re-checked later. */
  sha256: string;
  retrievedAt: string;
  /** Upstream caching headers, useful for spotting a changed file later. */
  lastModified: string | null;
  etag: string | null;
  discoveredIn: string;
  route: DiscoveryRoute;
  /** The preserved file this one was reached from, for NetworkLink chains. */
  parentId: string | null;
  depth: number;
  inspection: FileInspection;
  notes: string[];
};

/** An attempt that did not yield a file, kept so the sweep is auditable. */
export type PreservationFailure = {
  url: string;
  route: DiscoveryRoute;
  discoveredIn: string;
  kind: string;
  reason: string;
};

export type PreservationSweep = {
  id: string;
  startedAt: string;
  finishedAt: string;
  /** Candidate URLs considered, before fetching. */
  candidates: number;
  preserved: SourceFileRecord[];
  failures: PreservationFailure[];
  requestsSpent: number;
  bytesDownloaded: number;
  notes: string[];
  warnings: string[];
};

/** Human-readable summary of where a sweep's files came from. */
export function summariseRoutes(files: SourceFileRecord[]): Array<{ route: DiscoveryRoute; count: number }> {
  const counts = new Map<DiscoveryRoute, number>();
  for (const file of files) {
    counts.set(file.route, (counts.get(file.route) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([route, count]) => ({ route, count }))
    .sort((a, b) => b.count - a.count);
}

/** Files reached by a route the visible interface does not offer. */
export function unexposedFiles(files: SourceFileRecord[]): SourceFileRecord[] {
  return files.filter((file) => UNEXPOSED_ROUTES.has(file.route));
}
