'use client';

/**
 * Source Files — original KML/KMZ preserved from the source.
 *
 * Kept as its own screen rather than mixed into Export History, because the two
 * are different things and the interface should not invite anyone to treat them
 * alike. Everything here is a file the source published; nothing on this screen
 * was generated by the tool.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Empty, Notice, Panel, Row, Spinner } from '@/components/ui';
import { OriginBadge } from '@/components/origin-badge';
import type { DiscoveryRoute, FileInspection, PreservedFileKind } from '@/lib/preservation/types';

type SourceFile = {
  id: string;
  origin: 'original';
  url: string;
  finalUrl: string | null;
  kind: PreservedFileKind;
  filename: string;
  contentType: string | null;
  byteSize: number;
  size: string;
  sha256: string;
  retrievedAt: string;
  lastModified: string | null;
  etag: string | null;
  discoveredIn: string;
  route: DiscoveryRoute;
  routeLabel: string;
  unexposed: boolean;
  parentId: string | null;
  depth: number;
  inspection: FileInspection;
  notes: string[];
  downloadUrl: string;
};

type SweepResult = {
  preservedCount: number;
  unexposedCount: number;
  candidates: number;
  routes: Array<{ route: string; label: string; count: number }>;
  failures: Array<{ url: string; kind: string; reason: string }>;
  notes: string[];
  warnings: string[];
  requestsSpent: number;
};

export default function SourceFilesPage() {
  const [files, setFiles] = useState<SourceFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [sweeping, setSweeping] = useState(false);
  const [sweep, setSweep] = useState<SweepResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await fetch('/api/source-files');
      const payload = (await response.json()) as { files?: SourceFile[] };
      setFiles(payload.files ?? []);
    } catch {
      setFiles([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const runSweep = async () => {
    setSweeping(true);
    setError(null);
    try {
      const response = await fetch('/api/preserve', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({}),
      });
      const payload = (await response.json()) as SweepResult & { error?: string; detail?: string };
      if (!response.ok) {
        setError(payload.detail ?? payload.error ?? 'The sweep could not be completed.');
        return;
      }
      setSweep(payload);
      await load();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'The sweep could not be completed.');
    } finally {
      setSweeping(false);
    }
  };

  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    if (!needle) return files;
    return files.filter(
      (file) =>
        file.filename.toLowerCase().includes(needle) ||
        file.url.toLowerCase().includes(needle) ||
        (file.inspection.documentName ?? '').toLowerCase().includes(needle),
    );
  }, [files, query]);

  const unexposedCount = files.filter((file) => file.unexposed).length;

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">Source files</h1>
          <p className="mt-1 max-w-3xl text-sm text-[var(--color-ink-muted)]">
            Original KML and KMZ files retrieved from the source and preserved byte for byte. These are the
            files the source published — nothing on this page was generated by this tool.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <input
            type="search"
            className="field max-w-xs"
            placeholder="Search filename or URL…"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            aria-label="Search source files"
          />
          <button type="button" className="btn btn-primary" onClick={() => void runSweep()} disabled={sweeping}>
            {sweeping ? 'Sweeping…' : 'Sweep for source files'}
          </button>
        </div>
      </header>

      <Notice tone="info" title="Original, not reconstructed">
        A file listed here is served back exactly as it was received, with its SHA-256 recorded so the copy can
        be proven identical. Documents this tool <em>generates</em> from map geometry live under{' '}
        <strong>KML Export</strong> and <strong>Export History</strong>, are stamped{' '}
        <code className="mono">origin=reconstructed</code>, and are never presented as source files.
      </Notice>

      {error && <Notice tone="bad">{error}</Notice>}

      {sweep && (
        <Panel title="Last sweep">
          <div className="space-y-3">
            <dl className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <Stat label="Preserved" value={sweep.preservedCount} tone="good" />
              <Stat label="Not in the UI" value={sweep.unexposedCount} tone="accent" />
              <Stat label="Candidates" value={sweep.candidates} />
              <Stat label="Requests" value={sweep.requestsSpent} />
            </dl>

            {sweep.routes.length > 0 && (
              <div>
                <p className="label mb-1.5">How they were reached</p>
                <ul className="flex flex-wrap gap-1.5">
                  {sweep.routes.map((entry) => (
                    <li
                      key={entry.route}
                      className="chip border-[var(--color-border-strong)] bg-[var(--color-surface-raised)] text-[var(--color-ink-muted)]"
                    >
                      {entry.label} · {entry.count}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {sweep.warnings.map((warning) => (
              <Notice key={warning} tone="warn">
                {warning}
              </Notice>
            ))}
            {sweep.notes.map((note) => (
              <p key={note} className="text-xs text-[var(--color-ink-subtle)]">
                {note}
              </p>
            ))}

            {sweep.failures.length > 0 && (
              <details className="rounded-lg border border-[var(--color-border)] bg-[var(--color-canvas)] p-3">
                <summary className="cursor-pointer text-sm text-[var(--color-ink-muted)]">
                  {sweep.failures.length} candidate(s) were not preserved
                </summary>
                <ul className="mt-2 max-h-56 space-y-1 overflow-y-auto text-xs">
                  {sweep.failures.map((failure) => (
                    <li key={failure.url}>
                      <span className="mono break-all text-[var(--color-ink-subtle)]">{failure.url}</span>
                      <span className="block text-[var(--color-ink-muted)]">{failure.reason}</span>
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </div>
        </Panel>
      )}

      {loading ? (
        <Panel>
          <Spinner label="Loading preserved files…" />
        </Panel>
      ) : files.length === 0 ? (
        <Panel>
          <Empty title="No source files preserved yet">
            Run a sweep to look for KML and KMZ files the source publishes — including ones referenced only
            inside JavaScript bundles or reached through NetworkLinks in other KML documents, which the visible
            interface never offers.
          </Empty>
        </Panel>
      ) : (
        <>
          <p className="text-sm text-[var(--color-ink-muted)]">
            {files.length.toLocaleString()} file{files.length === 1 ? '' : 's'} preserved
            {unexposedCount > 0 && (
              <>
                {' · '}
                <span className="text-[var(--color-accent)]">
                  {unexposedCount.toLocaleString()} not reachable through the visible interface
                </span>
              </>
            )}
          </p>

          <div className="space-y-3">
            {filtered.map((file) => (
              <article key={file.id} className="panel p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <h2 className="mono text-sm font-semibold text-[var(--color-ink)]">{file.filename}</h2>
                    <p className="mono mt-0.5 break-all text-xs text-[var(--color-ink-subtle)]">{file.url}</p>
                  </div>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <OriginBadge origin="original" />
                    <span className="chip border-[var(--color-border-strong)] bg-[var(--color-surface-raised)] text-[var(--color-ink-muted)]">
                      {file.kind.toUpperCase()} · {file.size}
                    </span>
                    {file.unexposed && (
                      <span
                        className="chip border-[var(--color-accent)]/40 bg-[var(--color-accent-soft)] text-[var(--color-accent)]"
                        title="This file is not offered anywhere in the source's visible interface."
                      >
                        Not exposed in the UI
                      </span>
                    )}
                  </div>
                </div>

                <dl className="mt-3 grid gap-x-8 sm:grid-cols-2">
                  <Row label="Found" value={file.routeLabel} />
                  <Row
                    label="Placemarks"
                    value={
                      file.inspection.parseError
                        ? 'Not readable'
                        : `${file.inspection.placemarks.toLocaleString()} (${file.inspection.withGeometry.toLocaleString()} with geometry)`
                    }
                  />
                  <Row label="Retrieved" value={new Date(file.retrievedAt).toLocaleString()} />
                  <Row
                    label="Geometry"
                    value={file.inspection.geometryTypes.join(', ') || 'None reported'}
                  />
                </dl>

                {file.notes.map((note) => (
                  <Notice key={note} tone="warn">
                    {note}
                  </Notice>
                ))}

                {expanded === file.id && (
                  <dl className="mt-3 rounded-lg border border-[var(--color-border)] bg-[var(--color-canvas)] p-3">
                    <Row label="SHA-256" value={<span className="mono break-all">{file.sha256}</span>} />
                    <Row label="Bytes" value={file.byteSize.toLocaleString()} mono />
                    <Row label="Content type" value={file.contentType ?? 'Not declared'} mono />
                    <Row label="Discovered in" value={file.discoveredIn} />
                    <Row label="NetworkLink depth" value={String(file.depth)} mono />
                    {file.inspection.documentName && (
                      <Row label="Document name" value={file.inspection.documentName} />
                    )}
                    {file.inspection.networkLinks > 0 && (
                      <Row label="NetworkLinks" value={String(file.inspection.networkLinks)} mono />
                    )}
                    {file.lastModified && <Row label="Last modified" value={file.lastModified} mono />}
                    {file.etag && <Row label="ETag" value={file.etag} mono />}
                    {file.inspection.archiveEntries.length > 0 && (
                      <Row
                        label="Archive entries"
                        value={`${file.inspection.archiveEntries.length}: ${file.inspection.archiveEntries
                          .slice(0, 6)
                          .join(', ')}`}
                      />
                    )}
                    {file.inspection.parseError && (
                      <Row label="Parse error" value={file.inspection.parseError} />
                    )}
                  </dl>
                )}

                <div className="mt-3 flex gap-2">
                  <a className="btn btn-primary" href={file.downloadUrl}>
                    Download original
                  </a>
                  <button
                    type="button"
                    className="btn btn-ghost"
                    onClick={() => setExpanded(expanded === file.id ? null : file.id)}
                  >
                    {expanded === file.id ? 'Less' : 'Details'}
                  </button>
                </div>
              </article>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: number; tone?: 'good' | 'accent' }) {
  const colour =
    tone === 'good'
      ? 'text-[var(--color-good)]'
      : tone === 'accent'
        ? 'text-[var(--color-accent)]'
        : 'text-[var(--color-ink)]';
  return (
    <div>
      <dt className="label">{label}</dt>
      <dd className={`mono text-lg ${colour}`}>{value.toLocaleString()}</dd>
    </div>
  );
}
